### ISSUE TITLE
静的ページの作成

### ISSUE THREAD

**Issue by piyoketa** [poster-keisuke/nobel_lab.#122]
・「利用規約」「プライバシーポリシー」のページの作成

TODO by たにー
- [ ] 利用規約、プライバシーポリシーページのルーティングおよびViewの作成
- [ ] デザインの作成（中身は不要）

TODO by ちば
- [ ] 西岡くんから受け取った文面をたにーの決めたHTMLの構造に流し込む

**Comment by Atsuko-bbt** [comment]
プライバシーポリシーのview作りました
